# ------------------------------------------------------------------------------
# config.yaml
#
# Hydra configuration file for webhash-monitor
# Maintains settings for webpage requests and hashing behavior.
# ------------------------------------------------------------------------------
# Usage Examples:
#   python main.py options.timeout_seconds=15
#   python main.py options.hash_dir="./custom_hash_store"
#   python main.py request_headers.User-Agent="CustomBot/1.0"
# ------------------------------------------------------------------------------

options:
  # Request timeout in seconds
  timeout_seconds: 10

  # Maximal URLS allowed to check
  max_urls: 1000

  # Maximal directory size (50MB)
  max_dir_size: 52428800

  # Maximal size of the content returned by a request (50MB)
  max_content_size: 52428800

  # How often should the request repeated on failure
  max_retries: 3

  # Directory where webpage hashes are stored
  hash_dir: "./hash_store"


request_headers:
  # Standard headers to mimic a real browser request
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
  Accept-Encoding: "gzip, deflate, br, zstd"
  Accept-Language: "en-US,en;q=0.5"
  Cache-Control: "max-age=0"
  Connection: "keep-alive"
  Upgrade-Insecure-Requests: "1"

  # Default user agent string to reduce the chance of being blocked
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36"

# Add these so Hydra knows about the keys
url: null          # single URL
urls: []           # list of URLs
